package Ventanas;

import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import labmongodb.ConexionJavaMongo;
import org.bson.Document;

public class Consultas extends javax.swing.JFrame {


    public Consultas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_VolverCrear = new javax.swing.JButton();
        BotonC1 = new javax.swing.JButton();
        BotonC2 = new javax.swing.JButton();
        BotonC3 = new javax.swing.JButton();
        BotonC4 = new javax.swing.JButton();
        BotonC5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_VolverCrear.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        Boton_VolverCrear.setText("Volver");
        Boton_VolverCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverCrearActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_VolverCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, -1));

        BotonC1.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        BotonC1.setText("Consultar toda la información de la película con un título en particular");
        BotonC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonC1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        BotonC2.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        BotonC2.setText("Consultar toda la información de las películas de una franquicia en particular");
        BotonC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonC2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        BotonC3.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        BotonC3.setText("Consultar toda la información de las películas estrenadas en un rango de años específico");
        BotonC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonC3ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        BotonC4.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        BotonC4.setText("Consultar el nombre de película, género, año de estreno de todas las películas producidas por una compañía productora en particular.");
        BotonC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonC4ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        BotonC5.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        BotonC5.setText("Consultar la cantidad , la menor duración, la mayor duración y la duración promedio de las películas producidas por una compañía productora ");
        BotonC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonC5ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 2, 36)); // NOI18N
        jLabel1.setText("Seleccione la consulta que desee");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 540, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenInterfaz.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 921, 749));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_VolverCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverCrearActionPerformed
        JFrame Menu = new Menu();
        Menu.setLocationRelativeTo(Menu);
        Menu.setVisible(true);
        this.hide();
    }//GEN-LAST:event_Boton_VolverCrearActionPerformed

    private void BotonC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonC1ActionPerformed
        JFrame C1= new C1();
        C1.setLocationRelativeTo(C1);
        C1.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BotonC1ActionPerformed

    private void BotonC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonC2ActionPerformed
        JFrame C2 = new C2();
        C2.setLocationRelativeTo(C2);
        C2.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BotonC2ActionPerformed

    private void BotonC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonC3ActionPerformed
        JFrame C3= new C3();
        C3.setLocationRelativeTo(C3);
        C3.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BotonC3ActionPerformed

    private void BotonC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonC4ActionPerformed
        JFrame C4= new C4();
        C4.setLocationRelativeTo(C4);
        C4.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BotonC4ActionPerformed

    private void BotonC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonC5ActionPerformed
        JFrame C5= new C5();
        C5.setLocationRelativeTo(C5);
        C5.setVisible(true);
        this.hide();
    }//GEN-LAST:event_BotonC5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonC1;
    private javax.swing.JButton BotonC2;
    private javax.swing.JButton BotonC3;
    private javax.swing.JButton BotonC4;
    private javax.swing.JButton BotonC5;
    private javax.swing.JButton Boton_VolverCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
