/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author tmeji
 */
public class Crear extends javax.swing.JFrame {

    /**
     * Creates new form Crear
     */
    public Crear() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAddActores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Franquicia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Info_NombrePeli = new javax.swing.JTextField();
        Info_Genero = new javax.swing.JTextField();
        Info_Director = new javax.swing.JTextField();
        Info_Franquicia = new javax.swing.JTextField();
        Info_Pais = new javax.swing.JTextField();
        Info_Estreno = new javax.swing.JTextField();
        Info_Tiempo = new javax.swing.JTextField();
        Info_Compañia = new javax.swing.JTextField();
        Info_Actores = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAddActores.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        BotonAddActores.setText("Añadir más actores");
        getContentPane().add(BotonAddActores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jButton1.setText("Añadir película a la base de datos");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 690, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Pelicula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Género Película");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre del Director");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, -1));

        Franquicia.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        Franquicia.setForeground(new java.awt.Color(255, 255, 255));
        Franquicia.setText("Franquicia");
        getContentPane().add(Franquicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("País de rodaje de la película");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año de estreno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Duración en minutos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 170, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Compañia Productora");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Actores");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 70, -1));

        Info_NombrePeli.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        getContentPane().add(Info_NombrePeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 330, -1));

        Info_Genero.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        getContentPane().add(Info_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 330, 30));

        Info_Director.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        getContentPane().add(Info_Director, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 330, 30));

        Info_Franquicia.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        getContentPane().add(Info_Franquicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 330, 30));
        getContentPane().add(Info_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 300, 30));
        getContentPane().add(Info_Estreno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 200, 30));
        getContentPane().add(Info_Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 250, 30));
        getContentPane().add(Info_Compañia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 270, 30));
        getContentPane().add(Info_Actores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 310, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenInterfaz.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 921, 749));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAddActores;
    private javax.swing.JLabel Franquicia;
    private javax.swing.JTextField Info_Actores;
    private javax.swing.JTextField Info_Compañia;
    private javax.swing.JTextField Info_Director;
    private javax.swing.JTextField Info_Estreno;
    private javax.swing.JTextField Info_Franquicia;
    private javax.swing.JTextField Info_Genero;
    private javax.swing.JTextField Info_NombrePeli;
    private javax.swing.JTextField Info_Pais;
    private javax.swing.JTextField Info_Tiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
