package Ventanas;

import java.util.Arrays;
import java.util.List;
import javax.swing.JFrame;
import labmongodb.ConexionJavaMongo;

public class CrearCP extends javax.swing.JFrame {


    public CrearCP() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_AñadirCP = new javax.swing.JButton();
        Boton_VolverCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Info_NombreCP = new javax.swing.JTextField();
        Info_Fundacion = new javax.swing.JTextField();
        Info_Web = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_AñadirCP.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        Boton_AñadirCP.setText("Añadir Compañia Productora a la base de datos");
        Boton_AñadirCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AñadirCPActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_AñadirCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 420, -1));

        Boton_VolverCrear.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        Boton_VolverCrear.setText("Volver");
        Boton_VolverCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverCrearActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_VolverCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Compañia Productora");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 250, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Año de fundación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Página Web");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 170, -1));

        Info_NombreCP.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        getContentPane().add(Info_NombreCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 330, -1));

        Info_Fundacion.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        getContentPane().add(Info_Fundacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 330, 30));

        Info_Web.setFont(new java.awt.Font("Yu Gothic UI", 2, 18)); // NOI18N
        getContentPane().add(Info_Web, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 330, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenInterfaz.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 921, 749));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_VolverCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverCrearActionPerformed
        JFrame Principal2 = new Principal2();
        Principal2.setLocationRelativeTo(Principal2);
        Principal2.setVisible(true);
        this.hide();
    }//GEN-LAST:event_Boton_VolverCrearActionPerformed

    private void Boton_AñadirCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AñadirCPActionPerformed
        ConexionJavaMongo Compañia_Productora = new ConexionJavaMongo();
        String Año = Info_Fundacion.getText();
        int AñoConv = Integer.parseInt(Año);
       
        Compañia_Productora.Agregar_Compañia(Info_NombreCP.getText(),AñoConv,Info_Web.getText());
    }//GEN-LAST:event_Boton_AñadirCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_AñadirCP;
    private javax.swing.JButton Boton_VolverCrear;
    private javax.swing.JTextField Info_Fundacion;
    private javax.swing.JTextField Info_NombreCP;
    private javax.swing.JTextField Info_Web;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
